services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spring123
      MYSQL_DATABASE: learning
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local